### ISSUE TITLE
 Failed to run query [findAll] with parameters Array ( )

### ISSUE THREAD

**Issue by bobvdvalk** [DataDo/data#2]
Hi again,

I made a new repository in my project. But it fails to find all my data in my table. I checked if my mapping was correct and everything is green (see below). So it has to be good right? Then why can't it find all my data in the table?

My code:

api.php:

```
class Api
{
    public $id;
    public $host;
    public $key;
    public $token;
    public $datetime;
}
```

index.php:

```
$api_key = new Repository(Mawoo\Security\DataDoModels\Api::class, $pdo, 'id');
$api_key->checkDatabase();

```

Thank in advance for your help.

![knipsel](https://cloud.githubusercontent.com/assets/7026174/12833446/fa572bca-cba0-11e5-98c4-d116e2bb249e.PNG)

**Comment by bobvdvalk** [comment]
Found this when I did a findAll() in a var_dump

`Fatal error: Uncaught exception 'DataDo\Data\Exceptions\DslSyntaxException' with message 'Failed to run query [findAll] with parameters Array ( ) ' in C:\Users\Bob\IdeaProjects\CustomerService\vendor\datado\data\src\main\php\DataDo\Data\Repository.php:229 Stack trace: #0 [internal function]: DataDo\Data\Repository->DataDo\Data\{closure}() #1 C:\Users\Bob\IdeaProjects\CustomerService\vendor\datado\data\src\main\php\DataDo\Data\Repository.php(190): call_user_func_array(Object(Closure), Array) #2 C:\Users\Bob\IdeaProjects\CustomerService\index.php(36): DataDo\Data\Repository->__call('findAll', Array) #3 C:\Users\Bob\IdeaProjects\CustomerService\index.php(36): DataDo\Data\Repository->findAll() #4 {main} thrown in C:\Users\Bob\IdeaProjects\CustomerService\vendor\datado\data\src\main\php\DataDo\Data\Repository.php on line 229`
